id = "eu4mod"
name = "EU4 Modding"
version = "0.1.0"
schema_version = 1

[grammars.eu4mod]
repository = "https://github.com/DPetrusma/eu4-zed-tree-sitter-extension"
commit = "<commit-sha-of-generated-parser>"
